version: '3'
services:
  dind:
    image: docker:20.10-dind
    privileged: true
    networks:
      - jenkinsnet
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - jenkinsnet
    depends_on:
      - dind

networks:
  jenkinsnet:
    driver: bridge

volumes:
  jenkins-data:

